In [3]:
# %pip uninstall opencv-python
# %pip install opencv-contrib-python --user
# %pip install opencv-python --upgrade
# %pip install --upgrade pip
# %pip uninstall opencv-python; 
# %pip install opencv-python
# %pip install scikit-image
# %pip install libcudnn8

# %nvidia-smi -q
# %nvcc --version

In [15]:
import cv2
import math
import numpy as np
from skimage.draw import line
import os
import size_equalize
IMAGESIZE = 1000

os.chdir("C:/Users/user/Desktop/scoreDraw")
# print(os.getcwd())

In [16]:

exp_img_circle = cv2.imread("./CircleExample.jpg")
# draw_img_circle = cv2.imread("./SquareDraw.jpg")
# draw_img_circle = cv2.imread("./CircleDraw.jpg")
draw_img_circle = cv2.imread("./CircleDrawNew.jpg")
# draw_img_circle = cv2.imread("./CircleDrawDisconnect.jpg")
exp_img_square = cv2.imread("./SquareExample.jpg")
draw_img_square = cv2.imread("./SquareDraw.jpg")
# draw_img_square = cv2.imread("./SquareDrawDisconnect.jpg")
# draw_img_square = cv2.imread("./SquareDrawDisconnect4.jpg")
# draw_img_square = cv2.imread("./SquareDrawEdit2.jpg")

draw_img_circle = cv2.resize(draw_img_circle, (IMAGESIZE, IMAGESIZE))
exp_img_circle = cv2.resize(exp_img_circle, (IMAGESIZE, IMAGESIZE))
draw_img_square = cv2.resize(draw_img_square, (IMAGESIZE, IMAGESIZE))
exp_img_square = cv2.resize(exp_img_square, (IMAGESIZE, IMAGESIZE))

exp_org_circle = exp_img_circle.copy()
draw_org_circle = draw_img_circle.copy()
exp_org_square = exp_img_square.copy()
draw_org_square = draw_img_square.copy()


# cv2.imshow("ec",exp_img_circle)
# cv2.imshow("dc",draw_img_circle)
# cv2.imshow("es",exp_img_square)
# cv2.imshow("ds",draw_img_square)

# cv2.waitKey()
# cv2.destroyAllWindows()

In [17]:
# 잘라낼 좌표점
# 각 좌표가 비교 가능하게 초기화
# 좌표값 반환 함수 (4 꼭짓점 좌표 리스트 반환 )
left_up_exp_circle, left_down_exp_circle, right_up_exp_circle, right_down_exp_circle = size_equalize.get_extreme_points(exp_img_circle)
left_up_draw_circle, left_down_draw_circle, right_up_draw_circle, right_down_draw_circle = size_equalize.get_extreme_points(draw_img_circle)
left_up_exp_square, left_down_exp_square, right_up_exp_square, right_down_exp_square = size_equalize.get_extreme_points(exp_img_square)
left_up_draw_square, left_down_draw_square, right_up_draw_square, right_down_draw_square = size_equalize.get_extreme_points(draw_img_square)

In [26]:

# perspective Transform ( 예시 이미지 '원' )
orignal_pnt_exp_circle = np.float32([left_up_exp_circle, left_down_exp_circle, right_up_exp_circle, right_down_exp_circle])
move_pnt = np.float32([[0, 0], [0, 1000], [1000, 0], [1000, 1000]])

perspective_exp_circle = cv2.getPerspectiveTransform(orignal_pnt_exp_circle, move_pnt)
dst_exp_circle = cv2.warpPerspective(exp_org_circle.copy(), perspective_exp_circle, (1000, 1000))

# perspective Transform ( 아동 이미지 '원' )
orignal_pnt_draw_circle = np.float32([left_up_draw_circle, left_down_draw_circle, right_up_draw_circle, right_down_draw_circle])

perspective_draw_circle = cv2.getPerspectiveTransform(orignal_pnt_draw_circle, move_pnt)
dst_draw_circle = cv2.warpPerspective(draw_org_circle.copy(), perspective_draw_circle, (1000, 1000))

# perspective Transform ( 예시 이미지 '사각형' )
orignal_pnt_exp_square = np.float32([left_up_exp_square, left_down_exp_square, right_up_exp_square, right_down_exp_square])

perspective_exp_square = cv2.getPerspectiveTransform(orignal_pnt_exp_square, move_pnt)
dst_exp_square = cv2.warpPerspective(exp_org_square.copy(), perspective_exp_square, (1000, 1000))

# perspective Transform ( 아동 이미지 '사각형' )
orignal_pnt_draw_square = np.float32([left_up_draw_square, left_down_draw_square, right_up_draw_square, right_down_draw_square])

perspective_draw_square = cv2.getPerspectiveTransform(orignal_pnt_draw_square, move_pnt)
dst_draw_square = cv2.warpPerspective(draw_org_square.copy(), perspective_draw_square, (1000, 1000))

# cv2.imwrite("./result_image/draw_circle_cutresult.jpg", dst_draw_circle)
# cv2.imshow("exp circle", dst_exp_circle)
# cv2.imshow("draw circle", dst_draw_circle)
# cv2.imshow("exp square", dst_exp_square)
# cv2.imshow("draw square", dst_draw_square)
# cv2.waitKey()
# cv2.destroyAllWindows()


In [27]:
import circle_score
circle_score_result = circle_score.circle_score_result(dst_draw_circle, dst_exp_circle)

print(circle_score_result)


0.0027177298320024885
close to circle
close to circle
close to circle
Line coordinate : (0, 0), (0, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (1, 0), (1, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (2, 0), (2, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (3, 0), (3, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (4, 0), (4, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (5, 0), (5, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (6, 0), (6, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (7, 0), (7, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (8, 0), (8, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (9, 0), (9, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (10, 0), (10, 1000)
this line's intersect : 0
Entire intersect

In [9]:
# import re
# import os
# import cv2
# import numpy as np
# import natsort
# # %pip install natsort
# # %cd "E:/scoreDraw"

# os.chdir("C:/Users/user/Desktop/backup/scoreDraw")

# pathIn= "./images/horizontal"
# pathOut = "./result_image/horizontal.mp4"
# path = "./images/horizontal"

# paths = [os.path.join(path, i ) for i in os.listdir(path) if re.search(".jpg$", i )]
# paths = natsort.natsorted(paths)
# fps = 90

# frame_array = []
# for idx , path in enumerate(paths) : 
    
#     img = cv2.imread(path)
#     height, width, layers = img.shape
#     size = (width,height)
#     frame_array.append(img)

# out = cv2.VideoWriter(pathOut,cv2.VideoWriter_fourcc(*'FMP4'), fps, size)
# for i in range(len(frame_array)):
#     # writing to a image array
#     out.write(frame_array[i])
# out.release()


In [10]:

# pathIn= "./images/vertical"
# pathOut = "./result_image/vertical.mp4"
# path = "./images/vertical"

# paths = [os.path.join(path, i ) for i in os.listdir(path) if re.search(".jpg$", i )]
# paths = natsort.natsorted(paths)
# fps = 90

# frame_array = []
# for idx , path in enumerate(paths) : 
    
#     img = cv2.imread(path)
#     height, width, layers = img.shape
#     size = (width,height)
#     frame_array.append(img)

# out = cv2.VideoWriter(pathOut,cv2.VideoWriter_fourcc(*'FMP4'), fps, size)
# for i in range(len(frame_array)):
#     # writing to a image array
#     out.write(frame_array[i])
# out.release()

In [28]:
import square_score

square_score_result = square_score.square_score_result(dst_draw_square, dst_exp_square)
print(square_score_result)

[[810. 195.]] 179
[[810. 195.]] 134
[[810. 195.]] 90

[[111. 206.]] 1
[[111. 206.]] 87
[[111. 206.]] 42

[[139. 871.]] 46
[[139. 871.]] 93
[[139. 871.]] 2

[[806. 848.]] 90
[[806. 848.]] 138
[[806. 848.]] 178

0
square
Line coordinate : (0, 0), (0, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (1, 0), (1, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (2, 0), (2, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (3, 0), (3, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (4, 0), (4, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (5, 0), (5, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (6, 0), (6, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (7, 0), (7, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (8, 0), (8, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate 

In [24]:
import cv2
import math
import numpy as np
from skimage.draw import line
import os
import size_equalize
IMAGESIZE = 1000


os.chdir("C:/Users/user/Desktop/scoreDraw")

exp_img_diamond = cv2.imread("./DiamondExample.jpg")
draw_img_diamond = cv2.imread("./DiamondDraw.jpg")
draw_img_diamond = cv2.imread("./DiamondDrawEdit.jpg")
# draw_img_diamond = cv2.imread("./DiamondDraw2.jpg")
# draw_img_diamond = cv2.imread("./DiamondDrawFlash.jpg")

exp_img_diamond = cv2.resize(exp_img_diamond, (IMAGESIZE, IMAGESIZE))
draw_img_diamond = cv2.resize(draw_img_diamond, (IMAGESIZE, IMAGESIZE))

# cv2.imshow("exp", exp_img_diamond)
# cv2.imshow("draw", draw_img_diamond)
# cv2.waitKey()
# cv2.destroyAllWindows()

exp_org_diamond = exp_img_diamond.copy()
draw_org_diamond = draw_img_diamond.copy()

left_up_exp_diamond, left_down_exp_diamond, right_up_exp_diamond, right_down_exp_diamond = size_equalize.get_extreme_points(exp_img_diamond)
left_up_draw_diamond, left_down_draw_diamond, right_up_draw_diamond, right_down_draw_diamond = size_equalize.get_extreme_points(draw_img_diamond)

# perspective Transform ( 예시 이미지 '마름모' )
orignal_pnt_exp_diamond = np.float32([left_up_exp_diamond, left_down_exp_diamond, right_up_exp_diamond, right_down_exp_diamond])
move_pnt = np.float32([[0, 0], [0, 1000], [1000, 0], [1000, 1000]])

perspective_exp_diamond = cv2.getPerspectiveTransform(orignal_pnt_exp_diamond, move_pnt)
dst_exp_diamond = cv2.warpPerspective(exp_org_diamond.copy(), perspective_exp_diamond, (1000, 1000))

# perspective Transform ( 아동 이미지 '마름모' )
orignal_pnt_draw_diamond = np.float32([left_up_draw_diamond, left_down_draw_diamond, right_up_draw_diamond, right_down_draw_diamond])

perspective_draw_diamond = cv2.getPerspectiveTransform(orignal_pnt_draw_diamond, move_pnt)
dst_draw_diamond = cv2.warpPerspective(draw_org_diamond.copy(), perspective_draw_diamond, (1000, 1000))

cv2.imshow("exp", dst_exp_diamond)
cv2.imshow("draw", dst_draw_diamond)
cv2.waitKey()
cv2.destroyAllWindows()

In [22]:

import diamond_score

diamond_score_result = diamond_score.diamond_score_result(dst_draw_diamond, dst_exp_diamond)
print(diamond_score_result)

Line coordinate : (0, 0), (0, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (1, 0), (1, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (2, 0), (2, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (3, 0), (3, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (4, 0), (4, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (5, 0), (5, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (6, 0), (6, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (7, 0), (7, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (8, 0), (8, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (9, 0), (9, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (10, 0), (10, 1000)
this line's intersect : 0
Entire intersect : 0


Line coordinate : (11, 0), (11, 1000)
this line's intersect : 0

In [25]:
import cv2
import math
import numpy as np
from skimage.draw import line
import os
import size_equalize
IMAGESIZE = 1000

exp_img_tri = cv2.imread("./TriExample.jpg")
draw_img_tri = cv2.imread("./TriDraw.jpg")

exp_img_tri = cv2.resize(exp_img_tri, (IMAGESIZE, IMAGESIZE))
draw_img_tri = cv2.resize(draw_img_tri, (IMAGESIZE, IMAGESIZE))

exp_org_tri = exp_img_tri.copy()
draw_org_tri = draw_img_tri.copy()

left_up_exp_tri, left_down_exp_tri, right_up_exp_tri, right_down_exp_tri = size_equalize.get_extreme_points(exp_img_tri)
left_up_draw_tri, left_down_draw_tri, right_up_draw_tri, right_down_draw_tri = size_equalize.get_extreme_points(draw_img_tri)

# perspective Transform ( 예시 이미지 '마름모' )
orignal_pnt_exp_tri = np.float32([left_up_exp_tri, left_down_exp_tri, right_up_exp_tri, right_down_exp_tri])
move_pnt = np.float32([[0, 0], [0, 1000], [1000, 0], [1000, 1000]])

perspective_exp_tri = cv2.getPerspectiveTransform(orignal_pnt_exp_tri, move_pnt)
dst_exp_Tri = cv2.warpPerspective(exp_org_tri.copy(), perspective_exp_tri, (1000, 1000))

# perspective Transform ( 아동 이미지 '마름모' )
orignal_pnt_draw_tri = np.float32([left_up_draw_tri, left_down_draw_tri, right_up_draw_tri, right_down_draw_tri])

perspective_draw_tri = cv2.getPerspectiveTransform(orignal_pnt_draw_tri, move_pnt)
dst_draw_Tri = cv2.warpPerspective(draw_org_tri.copy(), perspective_draw_tri, (1000, 1000))

cv2.imshow("exp", dst_exp_Tri)
cv2.imshow("draw", dst_draw_Tri)
cv2.waitKey()
cv2.destroyAllWindows()